name: build

on:
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, Win32]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create Build Environment ${{matrix.platform}}
      shell: cmd
      run: cmake -E make_directory %GITHUB_WORKSPACE%\build-${{matrix.platform}}

    - name: Configure ${{matrix.platform}}
      shell: cmd
      run: cmake -G "Visual Studio 16 2019" -A ${{matrix.platform}} -S %GITHUB_WORKSPACE% -B %GITHUB_WORKSPACE%\build-${{matrix.platform}}

    - name: Build ${{matrix.platform}}
      shell: cmd
      run: cmake --build %GITHUB_WORKSPACE%\build-${{matrix.platform}} --config %BUILD_TYPE%

    
